node {
// Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server "01"
    def buildInfo = Artifactory.newBuildInfo() 

 
  stage('GIT CheckOut') {
    git branch: 'development ', url: 'https://github.com/amitvashisttech/mindtree-devops-27April2020.git'
  }

  def project_path = "petclinic-code"
  
  dir(project_path) {

  stage('Maven-Clean') {
    sh label: '', script: 'mvn clean'
  }

  stage('Maven-Compile') {
    sh label: '', script: 'mvn compile'
  }
  
  stage('Maven-Test') {
    sh label: '', script: 'mvn test'
  }
  
  stage('Maven-Package') {
    sh label: '', script: 'mvn package'
  }
   
  stage('SonarQube analysis' ) {
    withSonarQubeEnv('Sonar') { 
        sh 'mvn sonar:sonar'
    }     
  }

  stage('Build Managment') {
      def uploadSpec = """{
	 "files": [
	{
	"pattern": "**/*.war",
	"target": "libs-snapshot"
        }
	]
	}"""
	server.upload spec: uploadSpec
    }


    stage('Publish build info') {
    server.publishBuildInfo buildInfo
    }

  stage('Stage Deployment- Env Docker') {
    sh label: '', script: 'docker-compose up -d --build'
  }
 }
}
